
package com.xdev.rcdemo.hashing.ui;

import com.vaadin.navigator.ViewChangeListener;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.xdev.ui.XdevButton;
import com.xdev.ui.XdevGridLayout;
import com.xdev.ui.XdevHorizontalLayout;
import com.xdev.ui.XdevLabel;
import com.xdev.ui.XdevView;
import com.xdev.ui.navigation.Navigation;

public class MainView extends XdevView {

	/**
	 *
	 */
	public MainView() {
		super();
		this.initUI();
	}

	@Override
	public void enter(final ViewChangeListener.ViewChangeEvent event) {
		super.enter(event);

	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #button2}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button2_buttonClick(final Button.ClickEvent event) {
		Navigation.to("common").navigate();
	}

	/**
	 * Event handler delegate method for the {@link XdevButton} {@link #button}.
	 *
	 * @see Button.ClickListener#buttonClick(Button.ClickEvent)
	 * @eventHandlerDelegate Do NOT delete, used by UI designer!
	 */
	private void button_buttonClick(final Button.ClickEvent event) {
		Navigation.to("hashdemo").navigate();
	}

	/*
	 * WARNING: Do NOT edit!<br>The content of this method is always regenerated by
	 * the UI designer.
	 */
	// <generated-code name="initUI">
	private void initUI() {
		this.horizontalLayout = new XdevHorizontalLayout();
		this.gridLayout = new XdevGridLayout();
		this.button = new XdevButton();
		this.button2 = new XdevButton();
		this.label = new XdevLabel();

		this.button.setCaption("go to HashdemoView");
		this.button2.setCaption("go to CommonView");
		this.label.setValue("Go into code tab to view comments");

		this.gridLayout.setColumns(2);
		this.gridLayout.setRows(2);
		this.button.setWidth(200, Unit.PIXELS);
		this.button.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.button, 0, 0);
		this.button2.setWidth(200, Unit.PIXELS);
		this.button2.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.button2, 1, 0);
		this.label.setWidth(100, Unit.PERCENTAGE);
		this.label.setHeight(-1, Unit.PIXELS);
		this.gridLayout.addComponent(this.label, 0, 1, 1, 1);
		this.gridLayout.setComponentAlignment(this.label, Alignment.TOP_CENTER);
		this.gridLayout.setSizeUndefined();
		this.horizontalLayout.addComponent(this.gridLayout);
		this.horizontalLayout.setComponentAlignment(this.gridLayout, Alignment.MIDDLE_CENTER);
		this.horizontalLayout.setExpandRatio(this.gridLayout, 10.0F);
		this.horizontalLayout.setSizeFull();
		this.setContent(this.horizontalLayout);
		this.setSizeFull();

		this.button.addClickListener(event -> this.button_buttonClick(event));
		this.button2.addClickListener(event -> this.button2_buttonClick(event));
	} // </generated-code>

	// <generated-code name="variables">
	private XdevButton button2, button;
	private XdevLabel label;
	private XdevHorizontalLayout horizontalLayout;
	private XdevGridLayout gridLayout;
	// </generated-code>

}
